### ISSUE TITLE
Create consumable GitHub Actions workflow

### ISSUE THREAD

**Issue by d-e-s-o** [d-e-s-o/bpflint#9]
It would be great to provide an easily-consumable GitHub Actions workflow to automate linting of code bases in CI. Probably best to have an actual consumer for this ([BPF CI](https://github.com/kernel-patches/bpf/pulls), did I hear you knocking?), but in the end providing some sensible plumbing as a first version would also be important, and I suspect we could change the interface without too much ado. I am thinking of something along the lines of:
```yaml
  lint:
    name: Lint BPF C code
    runs-on: ubuntu-latest
    steps:
      - uses: d-e-s-o/bpflint@v0.0.1
        with:
          file: capabable.bpf.c
```
